### PR TITLE
Notification icon bug fix

### PR DESCRIPTION
**Pull request by namanyadav12**
Hopefully this will solve the issue

### CODE REVIEW

**Comment by kartikarora** [comment]
@namanyadav12 will have a look. Thanks!

**Comment by kartikarora** [comment]
The notification icon is still a white square. @namanyadav12

**Comment by kartikarora** [comment]
@namanyadav12 are you working on this?

**Comment by namanyadav12** [comment]
I was currently studying for my end semester exams and i will start working
4-5 days later after i reach home.So i have no plans for now.

**Comment by kartikarora** [comment]
Sure no problem :smile:

**Comment by kartikarora** [comment]
@namanyadav12 Are you willing to work on this? I'll close it if you are not.

**Comment by namanyadav12** [comment]
Oh Sorry i forgot about it. You can closeit  as i am not working on it
anymore.

**Pull request closed without merging**
