### PR TITLE
Added Calendar Support, Replaced SnackBar Library with android.support.design.widget.SnackBar Fixes #14

### LINKED ISSUE #14: Callendar Support
If the user wants, a new calendar event in the calendar app of the phone should be created.

### PR DESCRIPTION
**Pull request by anuraagbaishya**
The EditText to set date needs to be clicked twice to get the DatePicker. No idea why this is happening. Tested on Sony Xperia Z C6602 running Android 5.1.1 and Nexus 5 running Android 5.1.1. Working on both.

### CODE REVIEW

**Comment by kartikarora** [comment]
I'll have look once :)

**Comment by kartikarora** [comment]
Revert it back to 22. Don't change it 23 without the new permissions model, otherwise the app will break on Marshmallow. Or add the permissions model :P

**Comment by anuraagbaishya** [comment]
Reverted to 22

**Comment by kartikarora** [comment]
I'll see it on 8th now. Got an exam tomorrow and I'll be traveling after that. :stuck_out_tongue: Sorry for the delay.

Also, just refer the issues which were resolved in the PR using `#issue_no` so that's it's easier to follow and create new ones if required.

**Comment by kartikarora** [comment]
@anuraagbaishya, make the necessary changes in Parse app, I've added you as a collaborator.

**Comment by anuraagbaishya** [comment]
@chipset95 Added number field timeSinceEpoch on Parse

**Pull request merged**
